### ISSUE TITLE
[Fix] 구절 추가 화면 OCR 텍스트 변환시 인식 문제

### ISSUE THREAD

**Issue by myhan601** [dogaegirl6mo/Dokgi#104]
## 📝 이슈 요약

- 구절 추가 화면 OCR 텍스트 변환시 인식 문제

## ✅ 체크 리스트

- [x] placeholder 속성으로 되는것 수정

**Comment by suri0000** [comment]
해야할일 1, 2 뭐죠..ㅎ

**Comment by myhan601** [comment]
수정 했습니다.. ㅎ
