### ISSUE TITLE
[Design] 구절 작성화면 디테일

### ISSUE THREAD

**Issue by myhan601** [dogaegirl6mo/Dokgi#72]
## 📝 이슈 요약

- UI요소들에 대한 디테일을 수정합니다

## ✅ 체크 리스트

- [x] 텍스트뷰 스크롤시  연필 아이콘 위까지만 되게
- [x] 책 검색 부분 사진크기 줄이고, 책 제목, 저자 간격 벌리기
- [x] 구절 추가 책 검색 부분 searchBar 플레이스 홀더 폰트 크기 줄기
- [x]  searchBar 왼쪽 패딩 더 주기
- [x] 텍스트뷰 줄간격 조절

**Comment by suri0000** [comment]
제목과 라벨은 디자인이 좋을 것 같습니다!
